const $=s=>document.querySelector(s);let mode='all',data=null,tab='overview';const city=$('#city'),area=$('#area'),interest=$('#interest'),content=$('#content');const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));const arr=v=>Array.isArray(v)?v:[];
document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>{document.querySelectorAll('.mode').forEach(x=>x.classList.remove('active'));b.classList.add('active');mode=b.dataset.mode});
document.querySelectorAll('#tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');tab=b.dataset.tab;if(data)render()});
function list(title,icon,items){return `<div class="card"><h3>${icon} ${title}</h3><ul>${arr(items).map(x=>`<li><b>${esc(x.name||x.title||x)}</b>${x.street?` — ${esc(x.street)}`:''}${x.description?`<br>${esc(x.description)}`:''}</li>`).join('')}</ul></div>`}
function discoveries(items){return arr(items).map(d=>`<div class="card"><small>${esc(d.category)}</small><h3>${esc(d.name)}</h3><p>${esc(d.description)}</p>${d.area?`<span class="tag">📍 ${esc(d.area)}</span>`:''}${d.street?`<span class="tag">🛣 ${esc(d.street)}</span>`:''}${d.season?`<span class="tag">🍁 ${esc(d.season)}</span>`:''}${d.nearest_station?`<span class="tag">🚇 ${esc(d.nearest_station)}</span>`:''}${d.historical_reference?`<p><b>Historical reference:</b> ${esc(d.historical_reference)}</p>`:''}${d.etiquette?`<p><b>Tip / etiquette:</b> ${esc(d.etiquette)}</p>`:''}${d.pair_with?`<p><b>Pair with:</b> ${esc(d.pair_with)}</p>`:''}</div>`).join('')}
function render(){let g=data,html='';if(tab==='overview')html=`<div class="grid"><div class="card wide"><h3>🧭 Overview</h3><p>${esc(g.summary)}</p><span class="tag">🕐 ${esc(g.best_time)}</span><span class="tag">⏱ ${esc(g.duration)}</span><span class="tag">💰 ${esc(g.budget)}</span><span class="tag">🚇 ${esc(g.nearest_station)}</span></div>${list('Best Areas / Streets','📍',g.areas)}<div class="card wide"><h3>✨ Auto Discover</h3><div class="grid">${discoveries(g.discoveries)}</div></div>${list('Local Tips','💡',arr(g.tips).map(x=>({name:x})))}</div>`;
if(tab==='stories')html=`<div class="grid">${arr(g.stories).map(s=>`<div class="card story"><small>${esc(s.type)}</small><h3>${esc(s.title)}</h3><p>${esc(s.story)}</p><span class="tag">📍 ${esc(s.area)}</span><span class="tag">✓ ${esc(s.verification)}</span><p><b>Why it matters:</b> ${esc(s.why_it_matters)}</p></div>`).join('')}</div>`;
if(tab==='attractions')html=`<div class="grid">${list('Attractions','🏛️',g.attractions)}${list('Photo / Check-in','📸',g.photo_spots)}<div class="card wide"><h3>🍁 Seasonal / Photo / Campus Discoveries</h3><div class="grid">${discoveries(g.discoveries)}</div></div></div>`;
if(tab==='food')html=`<div class="grid">${list('Food & Drink','🍜',g.food)}${list('Cafés / Specialties','☕',g.cafes)}</div>`;
if(tab==='shopping')html=`<div class="grid">${list('Shopping','🛍️',g.shopping)}${list('What to Buy','🎁',g.what_to_buy)}</div>`;
if(tab==='route')html=`<div class="card"><h3>🚶 Suggested Route</h3>${arr(g.route).map((r,i)=>`<div class="route"><div class="num">${i+1}</div><div><b>${esc(r.name)}</b> — ${esc(r.area)}<br>${esc(r.note)} <span class="tag">${esc(r.time)}</span></div></div>`).join('')}</div>`;
if(tab==='social')html=`<div class="grid"><div class="card wide"><h3>📱 Facebook / Instagram</h3><pre>${esc(g.social_caption)}</pre></div><div class="card wide"><h3>✂️ Short Caption</h3><pre>${esc(g.short_caption)}</pre></div></div>`;content.innerHTML=html}
$('#go').onclick=async()=>{if(!city.value.trim())return;$('#status').textContent='GENERATING…';content.className='empty';content.textContent='Creating guide…';try{const r=await fetch('/api/guide',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({city:city.value.trim(),area:area.value.trim(),interest:interest.value,mode})});const j=await r.json();if(!r.ok)throw Error(j.error||'Generation failed');data=j;$('#title').textContent=[j.area||area.value,j.city].filter(Boolean).join(' — ');$('#intro').textContent=j.summary;$('#copy').hidden=$('#maps').hidden=false;$('#chips').innerHTML=arr(j.areas).map(a=>`<button class="chip">${esc(a.name)}</button>`).join('');document.querySelectorAll('.chip').forEach((b,i)=>b.onclick=()=>{area.value=j.areas[i].name;mode='area'});content.className='';tab='overview';document.querySelectorAll('#tabs button').forEach(x=>x.classList.toggle('active',x.dataset.tab==='overview'));render();$('#status').textContent='READY'}catch(e){content.innerHTML=`<div class="card">${esc(e.message)}<br><br>ตรวจสอบ OPENAI_API_KEY ใน Vercel แล้ว Redeploy</div>`;$('#status').textContent='ERROR'}};
$('#copy').onclick=()=>navigator.clipboard.writeText(JSON.stringify(data,null,2));$('#maps').onclick=()=>window.open('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent([area.value,city.value].filter(Boolean).join(' ')),'_blank');
