export default async function handler(req,res){
  if(req.method!=="POST")return res.status(405).json({error:"Method not allowed"});
  try{
    const {place="",story=null,context={}}=req.body||{};
    if(!story)return res.status(400).json({error:"Select a story first"});
    if(!process.env.OPENAI_API_KEY)return res.status(500).json({error:"OPENAI_API_KEY is not configured"});
    const style=`TRAVEL STORY v1.7 SIGNATURE STYLE (mandatory): cheerful hand-painted watercolor + coloured-pencil travel scrapbook / illustrated city-guide on warm ivory paper. The mood must feel playful, charming, optimistic, youthful and inviting — NEVER serious, solemn, museum-like, documentary, cinematic or photorealistic. Use simplified friendly shapes, loose pencil outlines, soft watercolor blooms, small doodles and handcrafted imperfections. Palette: fresh sky blue, coral, peach, butter yellow, sage/mint green, lavender and warm terracotta with plenty of clean cream negative space. People are cute editorial travel characters with warm expressions and slightly simplified proportions, not realistic portraits. Architecture and landmarks remain recognizable and geographically accurate, but render them lightly and delightfully rather than with heavy historical realism. Avoid sepia, muddy brown dominance, military/documentary mood, dramatic shadows, hyper-detailed realism, glossy 3D, anime, corporate vector art and photo-collage aesthetics.`;
    const prompt=`Create a bright landscape travel-journal illustration (3:2) for a story about ${place}.\n\n${style}\n\nTitle: ${story.title}\nStory: ${story.story}\nLocation: ${story.location}\nVerified context: ${JSON.stringify(context.verify||{})}\nVisual context: ${JSON.stringify(context.visual||{})}\n\nCONTENT ACCURACY: Keep the key landmark, architecture, local craft/food and cultural context recognizable and accurate. Do not depict uncertain legends as fact.\n\nCOMPOSITION RULES — v1.7 (mandatory): Make it feel like a joyful illustrated travel diary, not a historical reconstruction. ONE IMAGE = ONE FRIENDLY PRIMARY STORY. Use one sunny, welcoming hero scene as the main visual (about 65%). If useful, add only 2–3 SMALL floating scrapbook vignettes (together no more than 25%) for craft, food, history or local details. Vignettes should have soft watercolor edges or playful sketch bubbles — never hard cinematic montage seams. Keep strong breathing room and an easy visual flow. Show everyday travel life: strolling visitors, cafés, flowers, market details, small objects and cheerful human moments when relevant. Historical elements must be small, charming supporting memories rather than dominant portraits. Never make weapons, military vehicles, rulers, factories, monuments or machinery visually dominant unless the selected story is specifically about them. If such an object is necessary, soften and reduce it to a small supporting vignette.\n\nREFERENCE FEEL: premium illustrated travel guide / cute editorial travel journal / watercolor city diary — lively like a hand-drawn holiday notebook, with the freshness and friendliness of the approved Oxford example.\n\nLAYOUT: image only for the app hero illustration. Do not generate headings, captions, labels, logos, UI, watermarks, borders, itinerary cards or readable text inside the image.`;
    const r=await fetch("https://api.openai.com/v1/images/generations",{method:"POST",headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({model:process.env.OPENAI_IMAGE_MODEL||"gpt-image-2",prompt,size:"1536x1024",quality:"medium",output_format:"webp"})});
    const d=await r.json();
    if(!r.ok)throw new Error(d?.error?.message||"Image generation failed");
    const item=d?.data?.[0]||{};
    const image=item.b64_json?`data:image/webp;base64,${item.b64_json}`:item.url;
    if(!image)throw new Error("Image generation returned no image");
    return res.status(200).json({image,prompt,revised_prompt:item.revised_prompt||""});
  }catch(e){console.error(e);return res.status(500).json({error:e?.message||"Illustration failed"})}
}
